'use client';
import {useState} from 'react';
import {Fan,Lightbulb,LockKeyhole,Wifi,Check,Smartphone,ScanFace,Camera,Activity,Power,ArrowUpRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {rooms,packages,WHATSAPP} from '@/data/experience';
export function RoomSelector({room,onChange}:{room:number,onChange:(n:number)=>void}){return <Tabs value={String(room)} onValueChange={v=>onChange(Number(v))} className="room-selector"><TabsList aria-label="Choose a room">{rooms.map((r,i)=><TabsTrigger value={String(i)} key={r.name}>{r.name}</TabsTrigger>)}</TabsList>{rooms.map((r,i)=><TabsContent key={r.name} value={String(i)}><div className="room-detail"><span className="eyebrow">SCENE / {r.scene}</span><p>{r.copy}</p><div className="chips">{r.devices.map(d=><span key={d}>{d}</span>)}</div></div></TabsContent>)}</Tabs>}
export function PackageExplorer(){const [path,setPath]=useState(0);const [tier,setTier]=useState('Silver');return <div className="package-explorer"><Tabs value={String(path)} onValueChange={v=>{setPath(Number(v));setTier(packages[Number(v)].tiers[0])}}><TabsList aria-label="Solution type">{packages.map((p,i)=><TabsTrigger key={p.name} value={String(i)}>{p.name}</TabsTrigger>)}</TabsList>{packages.map((p,i)=><TabsContent value={String(i)} key={p.name}><p>{p.intro}</p><div className="tier-selector" role="group" aria-label="Package tier">{p.tiers.map(t=><button key={t} aria-pressed={tier===t} onClick={()=>setTier(t)}>{t}</button>)}</div><div className="package-caption">EXPLORE {tier.toUpperCase()} · CUSTOMIZABLE</div><ul>{p.features.map(f=><li key={f}><Check size={15}/>{f}</li>)}</ul><small>Available categories shown. Exact inclusions and compatibility are confirmed when planning your package.</small><a className="gold-button" href={WHATSAPP} target="_blank" rel="noopener noreferrer">CUSTOMIZE MY PLAN <ArrowUpRight size={17}/></a></TabsContent>)}</Tabs></div>}
export function DeviceStateOverlay({chapter,p}:{chapter:number,p:number}){
 const step=(n:number)=>Math.min(n-1,Math.floor(p*n));
 if(chapter===0)return <div className={`scene-callout ${p>.12?'awake':''}`}><Lightbulb size={17}/><div>LIVING ROOM<span>{p>.12?'Light on · Welcome home':'Ready when you are'}</span></div><span className="status-dot"/></div>;
 if(chapter===2)return <div className="device-panel retrofit"><div className="panel-top"><Wifi size={18}/><span>THE RETROFIT LAYER</span></div><div className="retrofit-compare"><div><Power size={38}/><strong>FAMILIAR SWITCH</strong><small>Existing appliances</small></div><div className="connected-side" style={{clipPath:`inset(0 ${100-p*100}% 0 0)`}}><Wifi size={38}/><strong>CONNECTED CONTROL</strong><small>App + voice + IoT hub</small></div><div className="reveal-line" style={{transform:`translateX(${p*100}%)`}}/></div><div className="chips"><span>LIGHTS</span><span>FANS</span><span>AC</span><span>SOCKETS</span></div><small>Installation and appliance compatibility assessed for your home.</small></div>;
 if(chapter===3){const scenes=['WELCOME','FOCUS','RELAX'];return <div className="device-panel"><div className="panel-top"><Lightbulb size={19}/><span>SMART LIGHT CONTROL</span><span className="status-dot"/></div><div className="big-reading">{scenes[step(3)]}</div><div className="light-meter"><i style={{transform:`scaleX(${.35+.6*Math.sin(p*Math.PI)})`}}/></div><div className="split"><span>{step(3)===1?'Brighter & cooler':'Soft & warm'}</span><span>RGB LED STRIP</span></div><div className="voice">“Turn on the living room lights.”</div><div className="chips"><span>VOICE COMMAND</span><span>APP CONTROL</span></div></div>}
 if(chapter===4)return <div className="device-panel"><div className="panel-top"><Fan className={p>.1?'fan-spin':''} style={{animationDuration:`${3-p*2.6}s`}} size={26}/><span>SCENE / ARRIVE HOME</span></div><div className="comfort-values"><div><span>FAN SPEED</span><strong>0{step(4)}<small> / 03</small></strong></div><div><span>COMFORT SETPOINT</span><strong>{(27-p*4).toFixed(1)}°</strong></div></div><div className="split"><span>AC MODE: {p>.1?'COOLING':'OFF'}</span><span>ILLUSTRATIVE</span></div><div className="chips"><span>SMART IR HUB</span><span>VOICE + APP</span></div></div>;
 if(chapter===5){const states=['Locked','Biometric access accepted','Keypad access accepted','Mobile app access','Remote unlock'];return <div className="device-panel"><div className="panel-top"><LockKeyhole size={20}/><span>ENTRY ACCESS</span></div><div className="access-icon">{step(5)===1?<ScanFace size={52}/>:step(5)>2?<Smartphone size={52}/>:<LockKeyhole size={52}/>}</div><div className="big-reading compact">{states[step(5)]}</div><div className="access-options">{['BIOMETRICS','KEYPAD','APP CONTROL','REMOTE UNLOCK','CAMERA VIEW'].map((s,i)=><span className={i===step(5)?'selected':''} key={s}>{s}</span>)}</div>{step(5)===4&&<div className="camera-view"><Camera size={18}/> ENTRY CAMERA VIEW · DEMO</div>}<small>Illustrative access states. No biometric information is collected.</small></div>}
 if(chapter===6)return <div className="device-panel"><div className="panel-top"><Activity size={19}/><span>MOTION & OCCUPANCY</span></div><div className="sensor-field"><span className="presence" style={{transform:`translateX(${(1-p)*150}px)`,opacity:p>.1?1:0}}>♙</span><i/><i/><i/></div>{['PRESENCE DETECTED','SCENE TRIGGERED','ALERT READY'].map((s,i)=><div key={s} className={`sensor-state ${p>(i+1)*.2?'selected':''}`}><Check size={15}/>{s}</div>)}</div>;
 if(chapter===7)return <div className="device-panel"><div className="panel-top"><Activity size={18}/><span>ENERGY MONITOR · CONCEPT</span></div><div className="big-reading compact">Current usage <span className="gold">{p>.5?'Moderate':'Low'}</span></div><div className="usage-chart" aria-label="Illustrative usage trend">{[30,48,38,64,52,82,69,45,60,38,28,34].map((v,i)=><i key={i} style={{height:v+'%',opacity:i/12<p?1:.25}}/>)}</div><div className="split"><span>LIGHTS · ACTIVE</span><span>AC · {p>.5?'ACTIVE':'INACTIVE'}</span></div><small>Illustrative data, not live readings or a savings estimate.</small></div>;
 if(chapter===8)return <div className="device-panel away-panel"><div className="panel-top"><Smartphone size={20}/><span>YOUR HOME, FROM ANYWHERE</span></div><div className="big-reading">AWAY MODE</div>{['Door locked','Lights off','Security / access ready','Optional surveillance view','Remote access confirmed'].map((s,i)=><div className={`sensor-state ${p>i*.18?'selected':''}`} key={s}><Check size={16}/>{s}</div>)}<small>Demonstration scene. No real home is connected.</small></div>;
 return null;
}
